services:
  db:
    image: mysql:8.0
    container_name: rental_db
    restart: always
    environment:
      MYSQL_DATABASE: rental_db
      MYSQL_USER: rental_user
      MYSQL_PASSWORD: rental_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: rental_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
