# Generated by Django 6.0.6 on 2026-07-11 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0, message='Цена должна быть больше нуля.')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='В жилье должна быть минимум 1 комната.'), django.core.validators.MaxValueValidator(20, message='Максимальное количество комнат — 20.')]),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
