# Generated by Django 6.0.6 on 2026-07-17 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_price_alter_listing_rooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='housing_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio')], default='apartment', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0, message='Price must be greater than zero.')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Must have at least 1 room.'), django.core.validators.MaxValueValidator(20, message='Maximum 20 rooms allowed.')]),
        ),
    ]
